name: test_backend

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run tests
        run: |
          cd backend
          go test -v ./...
